language: ruby
rvm:
- "1.9.3"
- "2.0.0"
# - "rbx-19mode"
# - "jruby-19mode"
# uncomment this line if your project needs to run something other than
# `rake`:
# script: bundle exec rspec spec
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

branches:
  only:
  - master
